apigateway:
  extends:
    file: docker-compose-common.yml
    service: apigateway
  volumes:
    - ../api-gateway-service/build/libs:/app
  links:
    - boardcommandside
    - taskcommandside
    - boardqueryside
    - taskqueryside
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

boardcommandside:
  extends:
    file: docker-compose-common.yml
    service: boardcommandside
  volumes:
    - ../board-command-side-service/build/libs:/app
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

taskcommandside:
  extends:
    file: docker-compose-common.yml
    service: taskcommandside
  volumes:
    - ../task-command-side-service/build/libs:/app
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

boardqueryside:
  extends:
    file: docker-compose-common.yml
    service: boardqueryside
  volumes:
    - ../board-query-side-service/build/libs:/app
  links:
    - mongodb
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

taskqueryside:
  extends:
    file: docker-compose-common.yml
    service: taskqueryside
  volumes:
    - ../task-query-side-service/build/libs:/app
  links:
    - mongodb
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

mongodb:
  extends:
    file: docker-compose-common.yml
    service: mongodb